export { Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Contact } from './Contact'
export { default as Professionals } from './Professionals'
export { default as Services } from './Services'
export { default as Pay } from './Pay'
export { default as Admin } from './Admin'
export { default as AddProfessional } from './AddProfessional'
export { default as AddCategory } from './AddCategory'
export { default as AddService } from './AddService'
export { default as AddProfessionalSubmit } from './AddProfessionalSubmit'
export { default as AddCategorySubmit } from './AddCategorySubmit'
export { default as AddServiceSubmit } from './AddServiceSubmit'
